---
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8.9
    container_name: rabbitmq
    volumes:
      - '~/.amaui/.rabbitmq:/var/lib/rabbitmq/mnesia'
    ports:
      - '5672:5672'
      - '15672:15672'

  rabbitmq-test:
    image: rabbitmq:3.8.9
    container_name: rabbitmq-test
    volumes:
      - '~/.amaui/.test/.rabbitmq:/var/lib/rabbitmq/mnesia'
    ports:
      - '4672:5672'
      - '14672:15672'
